### ISSUE TITLE
issues with RDST

### ISSUE THREAD

**Issue by TonyBagnall** [time-series-machine-learning/tsml-eval#28]
On Crop and StarLight, will see if its them all

Traceback (most recent call last):
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/numba/core/caching.py", line 482, in save
    data_name = overloads[key]
KeyError: ((array(float64, 3d, C), array(int64, 1d, C), int64, array(int64, 1d, C), uint64, float64, int64, int64, float64, type(CPUDispatcher(<function manhattan at 0x2aaed3602c10>)), bool, bool), ('x86_64-unknown-linux-gnu', 'icelake-server', '+64bit,+adx,+aes,-amx-bf16,-amx-int8,-amx-tile,+avx,+avx2,-avx512bf16,+avx512bitalg,+avx512bw,+avx512cd,+avx512dq,-avx512er,+avx512f,+avx512ifma,-avx512pf,+avx512vbmi,+avx512vbmi2,+avx512vl,+avx512vnni,-avx512vp2intersect,+avx512vpopcntdq,+bmi,+bmi2,-cldemote,+clflushopt,+clwb,-clzero,+cmov,+cx16,+cx8,-enqcmd,+f16c,+fma,-fma4,+fsgsbase,+fxsr,+gfni,+invpcid,-lwp,+lzcnt,+mmx,+movbe,-movdir64b,-movdiri,-mwaitx,+pclmul,+pconfig,+pku,+popcnt,-prefetchwt1,+prfchw,-ptwrite,+rdpid,+rdrnd,+rdseed,+rtm,+sahf,-serialize,+sgx,+sha,-shstk,+sse,+sse2,+sse3,+sse4.1,+sse4.2,-sse4a,+ssse3,-tbm,-tsxldtrk,+vaes,+vpclmulqdq,-waitpkg,+wbnoinvd,-xop,+xsave,+xsavec,+xsaveopt,+xsaves'), ('65c8737c21f796aa1873fa21486bc4db1d5e35bf6c0843eb6b81a7c9dc46affb', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/home/ajb/Code/tsml-estimator-evaluation/tsml_estimator_evaluation/experiments/classification_experiments.py", line 105, in <module>
    run_experiment(sys.argv)
  File "/gpfs/home/ajb/Code/tsml-estimator-evaluation/tsml_estimator_evaluation/experiments/classification_experiments.py", line 66, in run_experiment
    load_and_run_classification_experiment(
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/sktime/benchmarking/experiments.py", line 525, in load_and_run_classification_experiment
    run_classification_experiment(
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/sktime/benchmarking/experiments.py", line 321, in run_classification_experiment
    classifier.fit(X_train, y_train)
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/sktime/classification/base.py", line 191, in fit
    self._fit(X, y)
  File "/gpfs/home/ajb/Code/tsml-estimator-evaluation/tsml_estimator_evaluation/sktime_estimators/classification/rdst.py", line 17, in _fit
    self.clf.fit(X, y)
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/convst/classifiers/rdst_ridge.py", line 159, in fit
    self.transformer = self.transformer.fit(X, y)
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/convst/transformers/rdst.py", line 238, in fit
    self.shapelets_ = self.fitter(
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/numba/core/dispatcher.py", line 487, in _compile_for_args
    raise e
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/numba/core/dispatcher.py", line 972, in compile
    self._cache.save_overload(sig, cres)
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/numba/core/caching.py", line 664, in save_overload
    self._save_overload(sig, data)
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/numba/core/caching.py", line 674, in _save_overload
    self._cache_file.save(key, data)
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/numba/core/caching.py", line 491, in save
    self._save_index(overloads)
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/numba/core/caching.py", line 535, in _save_index
    data = self._dump(data)
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/numba/core/caching.py", line 563, in _dump
    return pickle.dumps(obj, protocol=-1)
  File "/gpfs/home/ajb/.conda/envs/eval/lib/python3.8/site-packages/numba/core/types/functions.py", line 486, in __getnewargs__
    raise ReferenceError("underlying object has vanished")
ReferenceError: underlying object has vanished

**Comment by MatthewMiddlehurst** [comment]
Not much we can do about this, and I think it is mostly relevant to the cluster. I managed to run all our datasets by removing the cache parameter on numba methods for the transform.

See https://github.com/baraline/convst/issues/24
