### ISSUE TITLE
[BUG] eval_name should be required in evaluate_clusterers_by_problem

### ISSUE THREAD

**Issue by TonyBagnall** [time-series-machine-learning/tsml-eval#304]
### Describe the bug

just using this, will list anything  minor I find here for reference

### Steps/Code to reproduce the bug

```from tsml_eval.evaluation import evaluate_clusterers_by_problem

clusterers = ["dba","dtw","euclidean","k-sc","k-shapes","kesba","soft-dba","ttc",
              "ushapelets"]
path = "C:\\Users\\Tony\OneDrive - University of " \
       "Southampton\\Research\\Papers\\2024\\KESBA\\Results\\"
#,"msm","twe"
from aeon.datasets.tsc_datasets import univariate_equal_length

if __name__ == "__main__":
    evaluate_clusterers_by_problem( clusterer_names=clusterers,
                                    load_path=path,
                                    error_on_missing=False,
                                    resamples = 1,
                                    save_path="C:\\Temp\\",
                                    dataset_names=list(univariate_equal_length),
    )
```

### Expected results

would put results in temp?

### Actual results

```python-traceback
Traceback (most recent call last):
  File "C:\Code\tsml-eval\tsml_eval\local\compare_clusterers.py", line 11, in <module>
    evaluate_clusterers_by_problem( clusterer_names=clusterers,
  File "C:\Code\tsml-eval\tsml_eval\evaluation\multiple_estimator_evaluation.py", line 526, in evaluate_clusterers_by_problem
    evaluate_clusterers(
  File "C:\Code\tsml-eval\tsml_eval\evaluation\multiple_estimator_evaluation.py", line 316, in evaluate_clusterers
    _evaluate_estimators(
  File "C:\Code\tsml-eval\tsml_eval\evaluation\multiple_estimator_evaluation.py", line 1065, in _evaluate_estimators
    save_path = save_path + "/" + eval_name + "/"
TypeError: can only concatenate str (not "NoneType") to str

**Comment by MatthewMiddlehurst** [comment]
should no longer crash with upcoming PR
